name: 'Upload app to TestFlight'
description: 'Uploads an app to Apple TestFlight'
author: 'Itty Bitty Apps Pty Ltd'
inputs:
  app-path:
    description: 'The path to the app (ipa etc)'
    required: true
  app-type:
    description: 'The type of app to upload (osx | ios | appletvos)'
    required: true
    default: 'ios'
  issuer-id:
    description: 'The AppStoreConnect API Key Issuer Identifier'
    required: true
  api-key-id:
    description: 'The Key ID for AppStore Connect API'
    required: true
  api-private-key:
    description: 'The PKCS8 format Private Key for AppStore Connect API'
    required: true
  retry-attempts-on-timeout:
    description: 'Number of retry attempts to perform if upload to AppStore TestFlight failed due to timeout from server end'
    required: false
    default: '0'
outputs:
  altool-response:
    description: 'XML output from altool'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
